<nav>
    <div id="logo_text">
            <img src = "styles/images/vng.jpg" class = "vngimage" alt = "VNG Games Logo"/>
    </div>
    <div class = "menu_container">
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="job.php">Career</a></li>
            <li><a href="apply.php">Apply</a></li>
        </ul>
    </div>
    <div class = "login_container">
        <ul>
            <li><a href="phpenhancement.php">Login</a></li>
        </ul>
    </div>

</nav>